### ISSUE TITLE
Plan to support wicket 7.0 and last version of jquery UI

### ISSUE THREAD

**Issue by dutrieux** [WiQuery/wiquery#48]
Hello,

Is there a plan to support wicket 7.0 and the last version of JQuery UI ?

Duto

**Comment by reiern70** [comment]
I'm not using wiquery right now on any of my project :-( 

I do not know if Hielke or any of the other commiters have interest in migrating it. Anyway, github allows to fork a project and submit PR.

**Comment by BeneStem** [comment]
they moved wiquery to wicketstuff and added wicket 7 support with my help.

you can find the repository here: https://github.com/wicketstuff/wiquery/issues/1

**Comment by dutrieux** [comment]
It's very a good news

thx for all your works
