### ISSUE TITLE
Release for 7?

### ISSUE THREAD

**Issue by astrapi69** [WiQuery/wiquery#52]
Hi there, in know this is a duplicate of #50 and #51 but there is no release in the mvn rep.

**Comment by martin-g** [comment]
The last comments at #50 discuss how to release at Maven central repo (thru Sonatype OSS).
I think this issue is a duplicate of #50. There is no need to have several issues for the same task.

**Comment by martin-g** [comment]
Please see https://github.com/WiQuery/wiquery/pull/50#issuecomment-152851097
