### ISSUE TITLE
jquery-ui-1.13.0 release

### ISSUE THREAD

**Issue by akramshuja** [WiQuery/wiquery#62]
Hello devs. Since jquery-ui-1.13.0 has been released last month and this library has a transitive dependency to the jquery-ui, is there any plan to release an update for wiquery-jquery so that it points to jqueru-ui-1.13.0 from the current 1.12.1 ?

**Comment by martin-g** [comment]
Hi @akramshuja !
Thanks for raising this!
Would you like sending us a Pull Request that updates JQueryUI to 1.13.0 ?

**Comment by akramshuja** [comment]
Sure, I can do it early next week

**Comment by akramshuja** [comment]
@martin-g Since this is the old release and we are already using 8.x, I would close this request and raise a new one in the other repo(using wicketstuff package).

**Comment by martin-g** [comment]
Right! Thanks!
